import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Cursor from "./_components/Cursor";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-black cursor-none scroll-smooth scroll-pt-2 select-none "
    >
      <body className={sora.className}>
        <Header />
        {children}
        <Cursor />
      </body>
    </html>
  );
}
